# Generated by Django 3.2.12 on 2024-05-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0002_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='managementSystem.church_branch'),
            preserve_default=False,
        ),
    ]
