# Generated by Django 3.2.12 on 2024-05-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0003_alter_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_list',
            old_name='security_absent',
            new_name='LCDC_Management_absent',
        ),
        migrations.RenameField(
            model_name='attendance_list',
            old_name='security_present',
            new_name='LCDC_Management_present',
        ),
        migrations.RenameField(
            model_name='attendance_list',
            old_name='security_total',
            new_name='LCDC_Management_total',
        ),
    ]
